name: Update Recent Activity
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update gist
        uses: angeloanan/activity-box-rs@v0.1.0
        env:
          GH_PAT: ${{ secrets.ACTIVITY_GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACTIVITY_GH_TOKEN }}
          GIST_ID: 041e96abbf9dbea96dd1456cf72b4473
          GH_USERNAME: angeloanan
